config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  get '/auth/twitter', as: :login

  get '/auth/:provider/callback', to: 'sessions#create'

  delete '/logout', as: :logout, to: 'sessions#destroy'


  resources :sessions, only: [:create, :destroy]
  resources :companies
  resources :email_addresses, except: [:index, :show]
  resources :phone_numbers, except: [:index, :show]
  resources :people
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :contact, required: false, polymorphic: true

  validates :number, :contact_id, presence: true
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number.contact }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number.contact }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content, location: @phone_number.contact }
    end
  end

  private
    def phone_number_params
      params.require(:phone_number).permit(:number, :contact_id, :contact_type)
    end
end

app/views/phone_numbers/_form.html.erb
<%= form_for(phone_number) do |f| %>
  <% if phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.hidden_field :contact_id %>
  </div>

  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_numbers/_phone_numbers.html.erb
<% phone_numbers.each do |number| %>
  <li class="phone-number"><%= number.number %>
    <%= link_to('edit', edit_phone_number_path(number)) %>
    <%= link_to('delete', phone_number_path(number), method: 'delete') %>
  </li>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phone Numbers</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.number %></td>
        <td><%= phone_number.contact_id %></td>
        <td><%= link_to 'Show', phone_number %></td>
        <td><%= link_to 'Edit', edit_phone_number_path(phone_number) %></td>
        <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Number', new_phone_number_path %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @phone_number.number %>
</p>

<p>
  <strong>Person:</strong>
  <%= @phone_number.contact_id %>
</p>

<%= link_to 'Edit', edit_phone_number_path(@phone_number) %> |
<%= link_to 'Back', phone_numbers_path %>