config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  get '/auth/twitter', as: :login

  get '/auth/:provider/callback', to: 'sessions#create'

  delete '/logout', as: :logout, to: 'sessions#destroy'


  resources :sessions, only: [:create, :destroy]
  resources :companies
  resources :email_addresses, except: [:index, :show]
  resources :phone_numbers, except: [:index, :show]
  resources :people
end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  # GET /email_addresses/new
  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /email_addresses/1/edit
  def edit
  end

  # POST /email_addresses
  # POST /email_addresses.json
  def create
    @email_address = EmailAddress.new(email_address_params)

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render :show, status: :created, location: @email_address.contact }
      else
        format.html { render :new }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_addresses/1
  # PATCH/PUT /email_addresses/1.json
  def update
    respond_to do |format|
      if @email_address.update(email_address_params)
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_address.contact }
      else
        format.html { render :edit }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.json
  def destroy
    @email_address.destroy
    respond_to do |format|
      format.html { redirect_to @email_address.contact, notice: 'Email address was successfully destroyed.' }
      format.json { head :no_content, location: @email_address.contact }
    end
  end

  private
    def email_address_params
      params.require(:email_address).permit(:address, :contact_id, :contact_type)
    end
end

app/views/email_addresses/_email_addresses.html.erb
<% email_addresses.each do |email| %>
  <li class="email-address"><%= email.address %>
    <%= link_to('edit', edit_email_address_path(email)) %>
    <%= link_to('delete', email_address_path(email), method: 'delete') %>
  </li>
<% end %>

app/views/email_addresses/_form.html.erb
<%= form_for(email_address) do |f| %>
  <% if email_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(email_address.errors.count, "error") %> prohibited this email_address from being saved:</h2>

      <ul>
      <% email_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.hidden_field :contact_id %>
  </div>

  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_addresses/edit.html.erb
<h1>Editing Email Address</h1>

<%= render 'form', email_address: @email_address %>

<%= link_to 'Show', @email_address %> |
<%= link_to 'Back', email_addresses_path %>

app/views/email_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Email Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @email_addresses.each do |email_address| %>
      <tr>
        <td><%= email_address.address %></td>
        <td><%= email_address.contact_id %></td>
        <td><%= link_to 'Show', email_address %></td>
        <td><%= link_to 'Edit', edit_email_address_path(email_address) %></td>
        <td><%= link_to 'Destroy', email_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Email Address', new_email_address_path %>

app/views/email_addresses/new.html.erb
<h1><%= "New Email Address for #{@email_address.contact}" %></h1>

<%= render 'form', email_address: @email_address %>

<%= link_to 'Back', email_addresses_path %>

app/views/email_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @email_address.address %>
</p>

<p>
  <strong>Person:</strong>
  <%= @email_address.contact_id %>
</p>

<%= link_to 'Edit', edit_email_address_path(@email_address) %> |
<%= link_to 'Back', email_addresses_path %>